import java.util.*;

// Node class to represent a node in the linked list
// class Node {
//     int data;
//         Node next = null;
//             Node(int data) {
//                     this.data = data;
//                         }
//                         }
//
//                         // SLL class to include various operations
//                         class SLL {
//                             Node head = null;
//
//                                 void addFirst(int data) {
//                                         Node newNode = new Node(data);
//                                                 newNode.next = head;
//                                                         head = newNode;
//                                                             }
//
//                                                                 void addLast(int data) {
//                                                                         Node newNode = new Node(data);
//                                                                                 if (head == null) {
//                                                                                             head = newNode;
//                                                                                                     } else {
//                                                                                                                 Node temp = head;
//                                                                                                                             while (temp.next != null)
//                                                                                                                                             temp = temp.next;
//                                                                                                                                                         temp.next = newNode;
//                                                                                                                                                                 }
//                                                                                                                                                                     }
//
//                                                                                                                                                                         int countNode() {
//                                                                                                                                                                                 Node temp = head;
//                                                                                                                                                                                         int count = 0;
//                                                                                                                                                                                                 while (temp != null) {
//                                                                                                                                                                                                             count++;
//                                                                                                                                                                                                                         temp = temp.next;
//                                                                                                                                                                                                                                 }
//                                                                                                                                                                                                                                         return count;
//                                                                                                                                                                                                                                             }
//
//                                                                                                                                                                                                                                                 void addAtPos(int data, int pos) {
//                                                                                                                                                                                                                                                         int total = countNode();
//                                                                                                                                                                                                                                                                 if (pos < 1 || pos > total + 1) {
//                                                                                                                                                                                                                                                                             System.out.println("Invalid position");
//                                                                                                                                                                                                                                                                                         return;
//                                                                                                                                                                                                                                                                                                 }
//
//                                                                                                                                                                                                                                                                                                         if (pos == 1) {
//                                                                                                                                                                                                                                                                                                                     addFirst(data);
//                                                                                                                                                                                                                                                                                                                                 return;
//                                                                                                                                                                                                                                                                                                                                         }
//
//                                                                                                                                                                                                                                                                                                                                                 if (pos == total + 1) {
//                                                                                                                                                                                                                                                                                                                                                             addLast(data);
//                                                                                                                                                                                                                                                                                                                                                                         return;
//                                                                                                                                                                                                                                                                                                                                                                                 }
//
//                                                                                                                                                                                                                                                                                                                                                                                         Node newNode = new Node(data);
//                                                                                                                                                                                                                                                                                                                                                                                                 Node temp = head;
//                                                                                                                                                                                                                                                                                                                                                                                                         for (int i = 1; i < pos - 1; i++) {
//                                                                                                                                                                                                                                                                                                                                                                                                                     temp = temp.next;
//                                                                                                                                                                                                                                                                                                                                                                                                                             }
//                                                                                                                                                                                                                                                                                                                                                                                                                                     newNode.next = temp.next;
//                                                                                                                                                                                                                                                                                                                                                                                                                                             temp.next = newNode;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                     void display() {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                             Node temp = head;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                     while (temp != null) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 System.out.print(temp.data + " -> ");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             temp = temp.next;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             System.out.println("null");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // Client class to interact with the linked list
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 public class Client {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     public static void main(String[] args) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Scanner sc = new Scanner(System.in);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     SLL sll = new SLL();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             char ch;
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     do {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 System.out.println("\nMenu:");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             System.out.println("1. addFirst");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         System.out.println("2. addLast");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     System.out.println("3. addAtPos");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 System.out.println("4. Display");
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             System.out.print("Enter your choice: ");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         int choice = sc.nextInt();
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     switch (choice) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     case 1:
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         System.out.print("Enter data: ");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             int data1 = sc.nextInt();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 sll.addFirst(data1);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     break;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     case 2:
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         System.out.print("Enter data: ");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             int data2 = sc.nextInt();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 sll.addLast(data2);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     break;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     case 3:
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         System.out.print("Enter data: ");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             int data3 = sc.nextInt();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 System.out.print("Enter position: ");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     int pos = sc.nextInt();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         sll.addAtPos(data3, pos);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             break;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             case 4:
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 sll.display();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     break;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     default:
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         System.out.println("Invalid choice!");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 System.out.print("Do you want to continue? (Y/N): ");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ch = sc.next().charAt(0);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     } while (ch == 'Y' || ch == 'y');
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             sc.close();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
//
